"""modified creator table, set server defaults

Revision ID: 08642a631d47
Revises: b2d5f8ca4e21
Create Date: 2026-09-10 18:19:44.397835

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08642a631d47'
down_revision = 'b2d5f8ca4e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brandcreatorlink',
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.PrimaryKeyConstraint('creator_id', 'brand_id')
    )
    op.add_column('creator', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    op.add_column('creator', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    op.create_index('ix_creator_region_trgm', 'creator', ['region'], unique=False, postgresql_using='gin', postgresql_ops={'region': 'gin_trgm_ops'})
    op.create_index('ix_creator_state_trgm', 'creator', ['state'], unique=False, postgresql_using='gin', postgresql_ops={'state': 'gin_trgm_ops'})
    op.drop_column('creator', 'categories_raw')
    op.drop_column('creator', 'languages_raw')
    op.alter_column('ingest_job', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('ingest_job', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('pitch', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('pitch', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('user', sa.Column('is_superadmin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('last_activity_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_activity_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'is_superadmin')
    op.alter_column('pitch', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('pitch', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('ingest_job', 'finished_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('ingest_job', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('creator', sa.Column('languages_raw', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('creator', sa.Column('categories_raw', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_creator_state_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'state': 'gin_trgm_ops'})
    op.drop_index('ix_creator_region_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'region': 'gin_trgm_ops'})
    op.drop_column('creator', 'region')
    op.drop_column('creator', 'state')
    op.drop_table('brandcreatorlink')
    # ### end Alembic commands ###