"""added creator commercials

Revision ID: 195e2b4160eb
Revises: 08642a631d47
Create Date: 2026-09-11 14:12:04.429714

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '195e2b4160eb'
down_revision = '08642a631d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercialpackage',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv4()'), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercialpackage_creator_id'), 'commercialpackage', ['creator_id'], unique=False)
    op.create_index('uq_creator_package_current', 'commercialpackage', ['creator_id', 'name'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_table('packagedeliverables',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv4()'), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('deliverable_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['commercialpackage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packagedeliverables_deliverable_type'), 'packagedeliverables', ['deliverable_type'], unique=False)
    op.create_index(op.f('ix_packagedeliverables_package_id'), 'packagedeliverables', ['package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packagedeliverables_package_id'), table_name='packagedeliverables')
    op.drop_index(op.f('ix_packagedeliverables_deliverable_type'), table_name='packagedeliverables')
    op.drop_table('packagedeliverables')
    op.drop_index('uq_creator_package_current', table_name='commercialpackage', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_index(op.f('ix_commercialpackage_creator_id'), table_name='commercialpackage')
    op.drop_table('commercialpackage')
    # ### end Alembic commands ###