"""modify server defaults across tables

Revision ID: 39bc44503933
Revises: 195e2b4160eb
Create Date: 2026-09-11 18:55:25.361450

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '39bc44503933'
down_revision = '195e2b4160eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigncreatorlink', 'product_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('campaigncreatorlink', 'product_ordered_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'company', ['gstin'])
    op.alter_column('creator', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('creator', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('creator', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('creator', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creator', 'region',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('creator', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('creator', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('creator', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'company', type_='unique')
    op.alter_column('campaigncreatorlink', 'product_ordered_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('campaigncreatorlink', 'product_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###