"""baseline v2

Revision ID: 6931ed079b00
Revises: 
Create Date: 2026-09-25 14:16:46.090168

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6931ed079b00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apify_run',
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('apify_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('run_input', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apify_run_actor'), 'apify_run', ['actor'], unique=False)
    op.create_index(op.f('ix_apify_run_run_id'), 'apify_run', ['run_id'], unique=True)
    op.create_index(op.f('ix_apify_run_status'), 'apify_run', ['status'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gstin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint("gstin = '' OR gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$'", name='ck_company_gstin_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_table('creator',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv4()'), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'YOUTUBE', 'LINKEDIN', 'FACEBOOK', 'OTHERS', 'NA', name='platformchoices'), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('followers', sa.Integer(), server_default='0', nullable=True),
    sa.Column('tier', sa.Enum('NANO', 'MICRO', 'MID_TIER', 'MACRO', 'MEGA', 'CELEB', 'NA', name='tierchoices'), nullable=False),
    sa.Column('avg_views', sa.Integer(), server_default='0', nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emails', postgresql.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::VARCHAR[]'), nullable=True),
    sa.Column('phones', postgresql.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::VARCHAR[]'), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stats_refreshed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'username', name='uq_creator_platform_username')
    )
    op.create_index('ix_creator_city_trgm', 'creator', ['city'], unique=False, postgresql_using='gin', postgresql_ops={'city': 'gin_trgm_ops'})
    op.create_index('ix_creator_name_trgm', 'creator', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_creator_region_trgm', 'creator', ['region'], unique=False, postgresql_using='gin', postgresql_ops={'region': 'gin_trgm_ops'})
    op.create_index('ix_creator_state_trgm', 'creator', ['state'], unique=False, postgresql_using='gin', postgresql_ops={'state': 'gin_trgm_ops'})
    op.create_index(op.f('ix_creator_stats_refreshed_at'), 'creator', ['stats_refreshed_at'], unique=False)
    op.create_index('ix_creator_username_trgm', 'creator', ['username'], unique=False, postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.create_table('ingest_job',
    sa.Column('job_id', sa.Uuid(), server_default=sa.text('uuidv4()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_job_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('errors_truncated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parent_job_id'], ['ingest_job.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_job_job_id'), 'ingest_job', ['job_id'], unique=True)
    op.create_index(op.f('ix_ingest_job_source'), 'ingest_job', ['source'], unique=False)
    op.create_index(op.f('ix_ingest_job_status'), 'ingest_job', ['status'], unique=False)
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), server_default='password', nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_currently_employed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('can_ingest', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gstin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("gstin = '' OR gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$'", name='ck_brand_gstin_format'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_brand_display_name_trgm', 'brand', ['display_name'], unique=False, postgresql_using='gin', postgresql_ops={'display_name': 'gin_trgm_ops'})
    op.create_table('categorycreatorlink',
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.PrimaryKeyConstraint('creator_id', 'category_id')
    )
    op.create_table('commercialpackage',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv4()'), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercialpackage_creator_id'), 'commercialpackage', ['creator_id'], unique=False)
    op.create_index('uq_creator_package_current', 'commercialpackage', ['creator_id', 'name'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_table('languagecreatorlink',
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('creator_id', 'language_id')
    )
    op.create_table('tagcreatorlink',
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('creator_id', 'tag_id')
    )
    op.create_table('brandcreatorlink',
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.PrimaryKeyConstraint('creator_id', 'brand_id')
    )
    op.create_table('packagedeliverables',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv4()'), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('deliverable_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['commercialpackage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packagedeliverables_deliverable_type'), 'packagedeliverables', ['deliverable_type'], unique=False)
    op.create_index(op.f('ix_packagedeliverables_package_id'), 'packagedeliverables', ['package_id'], unique=False)
    op.create_table('pitch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pitch_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_type', sa.Enum('BRAND_CORE', 'BRAND_OTHER', 'AGENCY', 'RETAINER_ACC', 'NA', name='orgtypechoices'), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('campaign_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requirement', sa.Enum('LIST', 'PLAN', 'LIST_AND_PLAN', 'CONTENT_BUCKETS', 'MEDIA_PLAN', 'PRODUCTION', 'CONTENT_BUCKETS_AND_LIST', 'DEMOGRAPHICS_DATA', 'NA', name='pitchrequirementchoices'), nullable=False),
    sa.Column('platform', postgresql.ARRAY(sa.Enum('INSTAGRAM', 'YOUTUBE', 'LINKEDIN', 'FACEBOOK', 'OTHERS', 'NA', name='platformchoices')), nullable=False),
    sa.Column('sales_lead', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('list_lead', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spreadsheet_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pitch_code'),
    sa.UniqueConstraint('spreadsheet_id')
    )
    op.create_index(op.f('ix_pitch_campaign_name'), 'pitch', ['campaign_name'], unique=False)
    op.create_table('campaign',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv4()'), nullable=False),
    sa.Column('campaign_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('month_name', sa.Enum('JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', name='monthchoices'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('campaign_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manager', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_names', postgresql.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::VARCHAR[]'), nullable=True),
    sa.Column('pitch_id', sa.Uuid(), nullable=True),
    sa.Column('spreadsheet_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'ON_HOlD', 'SCRAPPED', 'WIP', name='campaignstatuschoices'), nullable=False),
    sa.Column('expected_end_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('report_status', sa.Enum('COMPLETED', 'ON_HOlD', 'SCRAPPED', 'WIP', name='campaignstatuschoices'), nullable=False),
    sa.Column('report_completion_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id'),
    sa.UniqueConstraint('spreadsheet_id')
    )
    op.create_index(op.f('ix_campaign_campaign_code'), 'campaign', ['campaign_code'], unique=True)
    op.create_index(op.f('ix_campaign_campaign_name'), 'campaign', ['campaign_name'], unique=False)
    op.create_table('pitchcreatorlink',
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('pitch_id', sa.Uuid(), nullable=False),
    sa.Column('reel_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reel_story_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('video_story_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('static_carousel_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('event_store_visit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('short_form_videos_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reshare_short_form_videos_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dedicated_video_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('integrated_video_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('usage_rights', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ad_promo_rights', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('boosting', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), server_default='Under 45 days.', nullable=False),
    sa.Column('reel_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reel_story_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('video_story_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('static_carousel_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('short_form_videos_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reshare_short_form_videos_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dedicated_video_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('integrated_video_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rights_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('boosting_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('package_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('final_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('brand_cost', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch.id'], ),
    sa.PrimaryKeyConstraint('creator_id', 'pitch_id')
    )
    op.create_table('campaigncreatorlink',
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('is_dropped', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expected_views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('poc_name', sa.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::VARCHAR[]'), nullable=True),
    sa.Column('deliverables_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('initial_cost', sa.Integer(), nullable=False),
    sa.Column('final_cost', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('agency_fee', sa.Integer(), server_default='0', nullable=False),
    sa.Column('product_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_ordered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shipping_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('promotion_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reimbursement_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('additional_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('script_links', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shoot_date', sa.Date(), nullable=True),
    sa.Column('content_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('live_date', sa.Date(), nullable=True),
    sa.Column('live_links', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ig_reel_views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ig_reel_likes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ig_reel_comments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ig_reel_shares', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ig_reel_saves', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ig_story_views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ig_reel_reach', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ig_story_reach', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ig_avg_watch_time', sa.Interval(), server_default=sa.text("'0'::interval"), nullable=False),
    sa.Column('ig_total_watch_time', sa.Interval(), server_default=sa.text("'0'::interval"), nullable=False),
    sa.Column('ig_skip_rate_content', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_followers_view_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_non_followers_view_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_male_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_female_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_age_13_17_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_age_18_24_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_age_25_34_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_age_35_44_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_age_45_54_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_age_55_64_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_age_over_65_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_reels_ir_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('ig_reels_er_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('cpv', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('yt_views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('yt_likes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('yt_comments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('yt_er_perc', sa.Numeric(scale=2), server_default='0.00', nullable=False),
    sa.Column('yt_total_impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('yt_total_watch_time', sa.Interval(), server_default=sa.text("'0'::interval"), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.PrimaryKeyConstraint('creator_id', 'campaign_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigncreatorlink')
    op.drop_table('pitchcreatorlink')
    op.drop_index(op.f('ix_campaign_campaign_name'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_campaign_code'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_pitch_campaign_name'), table_name='pitch')
    op.drop_table('pitch')
    op.drop_index(op.f('ix_packagedeliverables_package_id'), table_name='packagedeliverables')
    op.drop_index(op.f('ix_packagedeliverables_deliverable_type'), table_name='packagedeliverables')
    op.drop_table('packagedeliverables')
    op.drop_table('brandcreatorlink')
    op.drop_table('tagcreatorlink')
    op.drop_table('languagecreatorlink')
    op.drop_index('uq_creator_package_current', table_name='commercialpackage', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_index(op.f('ix_commercialpackage_creator_id'), table_name='commercialpackage')
    op.drop_table('commercialpackage')
    op.drop_table('categorycreatorlink')
    op.drop_index('ix_brand_display_name_trgm', table_name='brand', postgresql_using='gin', postgresql_ops={'display_name': 'gin_trgm_ops'})
    op.drop_table('brand')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('language')
    op.drop_index(op.f('ix_ingest_job_status'), table_name='ingest_job')
    op.drop_index(op.f('ix_ingest_job_source'), table_name='ingest_job')
    op.drop_index(op.f('ix_ingest_job_job_id'), table_name='ingest_job')
    op.drop_table('ingest_job')
    op.drop_index('ix_creator_username_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_creator_stats_refreshed_at'), table_name='creator')
    op.drop_index('ix_creator_state_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'state': 'gin_trgm_ops'})
    op.drop_index('ix_creator_region_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'region': 'gin_trgm_ops'})
    op.drop_index('ix_creator_name_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_creator_city_trgm', table_name='creator', postgresql_using='gin', postgresql_ops={'city': 'gin_trgm_ops'})
    op.drop_table('creator')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    op.drop_table('category')
    op.drop_index(op.f('ix_apify_run_status'), table_name='apify_run')
    op.drop_index(op.f('ix_apify_run_run_id'), table_name='apify_run')
    op.drop_index(op.f('ix_apify_run_actor'), table_name='apify_run')
    op.drop_table('apify_run')
    # ### end Alembic commands ###