"""change campaign cr link table

Revision ID: 86a7cdfdddcf
Revises: 9536b3040da8
Create Date: 2026-08-22 20:21:40.276217

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '86a7cdfdddcf'
down_revision = '9536b3040da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigncreatorlink', 'ig_skip_rate_content',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_followers_view_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_non_followers_view_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_male_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_female_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_13_17_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_18_24_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_25_34_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_35_44_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_45_54_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_55_64_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_over_65_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_reels_ir_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_reels_er_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'yt_er_perc',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigncreatorlink', 'yt_er_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_reels_er_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_reels_ir_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_over_65_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_55_64_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_45_54_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_35_44_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_25_34_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_18_24_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_age_13_17_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_female_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_male_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_non_followers_view_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_followers_view_perc',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigncreatorlink', 'ig_skip_rate_content',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###