"""modify camp_cr_link

Revision ID: 8fde84a02def
Revises: 86a7cdfdddcf
Create Date: 2026-08-22 21:06:09.028693

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8fde84a02def'
down_revision = '86a7cdfdddcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigncreatorlink', 'script_links',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('campaigncreatorlink', 'shoot_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('campaigncreatorlink', 'content_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('campaigncreatorlink', 'live_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('campaigncreatorlink', 'live_links',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigncreatorlink', 'live_links',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('campaigncreatorlink', 'live_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('campaigncreatorlink', 'content_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('campaigncreatorlink', 'shoot_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('campaigncreatorlink', 'script_links',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###