"""editing: versions, is_active, can_edit, edit_log

Revision ID: df62919841a9
Revises: 6931ed079b00
Create Date: 2026-10-07 10:51:39.317305

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df62919841a9'
down_revision = '6931ed079b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edit_log_at', 'edit_log', ['at'], unique=False)
    op.create_index('ix_edit_log_record', 'edit_log', ['kind', 'record_id', 'at'], unique=False)
    op.add_column('brand', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('campaign', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('campaigncreatorlink', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('company', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('creator', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('creator', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_creator_is_active'), 'creator', ['is_active'], unique=False)
    op.add_column('pitch', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('pitchcreatorlink', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('user', sa.Column('can_edit', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # admins start with edit rights, so someone can hand them out
    op.execute('UPDATE "user" SET can_edit = true WHERE is_admin or is_superadmin')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'can_edit')
    op.drop_column('pitchcreatorlink', 'version')
    op.drop_column('pitch', 'version')
    op.drop_index(op.f('ix_creator_is_active'), table_name='creator')
    op.drop_column('creator', 'is_active')
    op.drop_column('creator', 'version')
    op.drop_column('company', 'version')
    op.drop_column('campaigncreatorlink', 'version')
    op.drop_column('campaign', 'version')
    op.drop_column('brand', 'version')
    op.drop_index('ix_edit_log_record', table_name='edit_log')
    op.drop_index('ix_edit_log_at', table_name='edit_log')
    op.drop_table('edit_log')
    # ### end Alembic commands ###